import type { Theme } from "../types";

/**
 * Calm: cool grey-blue slate, one quiet accent, and state colours with the
 * saturation turned down — a failed run still reads red, it just does not
 * shout. The inks keep 4.5:1; only their colourfulness is lowered.
 */
export const calm: Theme = {
  id: "calm",
  name: "Calm",
  description:
    "Soft slate greys, a grey-blue accent and muted state colours that inform without shouting.",
  light: {
    background: "#f3f5f7",
    foreground: "#1f2a35",
    card: "#fafbfc",
    "card-foreground": "#1f2a35",
    popover: "#fcfdfd",
    "popover-foreground": "#1f2a35",
    primary: "#4a6785",
    "primary-foreground": "#ffffff",
    secondary: "#e6eaef",
    "secondary-foreground": "#3a4756",
    muted: "#e9edf1",
    "muted-foreground": "#4f5d6b",
    accent: "#dfe6ee",
    "accent-foreground": "#1f2a35",
    destructive: "#b25450",
    "destructive-foreground": "#ffffff",
    border: "#d7dee6",
    input: "#cdd5de",
    ring: "#6c8bab",
    favourite: "#c29a3a",
    "favourite-surface": "#ecd79a",
    backdrop: "#1a2330",
    "badge-foreground": "#ffffff",
    "terminal-background": "#1e252d",
    "terminal-foreground": "#e3e8ee",
    "terminal-bar": "#28313b",
    "terminal-bar-foreground": "#c5ced8",
    "viz-grid": "#dbe1e8",

    "viz-muted": "#838d97",
    "viz-good": "#5c9a6c",
    "viz-warning": "#d6ac55",
    "viz-critical": "#c46660",
    "viz-running": "#567faa",
    "viz-merged": "#8b7bb5",
    "ink-good": "#3b6b47",
    "ink-warning": "#7a5a1c",
    "ink-critical": "#994440",
    "ink-running": "#3a608a",
    "ink-merged": "#5f5189",
    "ink-agent": "#2f6875",
    "ink-muted": "#5f6b77",
    "ink-repeat": "#2f6a66",
    "ink-wakeup": "#83486f",
    "mode-manual": "#5f6b77",
    "mode-plan": "#2f6a66",
    "mode-accept": "#6a4fa0",
    "mode-danger": "#9a4050",
    "mode-auto": "#7a5a1c",
    "kind-wsl": "#3a7050",
    "kind-windows": "#3d6698",
    "kind-cloud": "#6a5698",
    "kind-ssh": "#86602a",
  },
  dark: {
    background: "#14191f",
    foreground: "#e2e7ed",
    card: "#1b2129",
    "card-foreground": "#e2e7ed",
    popover: "#1f262f",
    "popover-foreground": "#e2e7ed",
    primary: "#8aa7c4",
    "primary-foreground": "#10161c",
    secondary: "#262e38",
    "secondary-foreground": "#c3ccd6",
    muted: "#252d36",
    "muted-foreground": "#a9b4c0",
    accent: "#2c3642",
    "accent-foreground": "#e2e7ed",
    destructive: "#d68a85",
    "destructive-foreground": "#14191f",
    border: "#2c3540",
    input: "#36414d",
    ring: "#8aa7c4",
    favourite: "#d9b95e",
    "favourite-surface": "#e6c973",
    backdrop: "#05080b",
    "badge-foreground": "#10161c",
    "terminal-background": "#11161b",
    "terminal-foreground": "#e2e7ed",
    "terminal-bar": "#1f262f",
    "terminal-bar-foreground": "#c3ccd6",
    "viz-grid": "#27303a",

    "viz-muted": "#7c8793",
    "viz-good": "#6fae80",
    "viz-warning": "#d9b56a",
    "viz-critical": "#d0817b",
    "viz-running": "#7ea3c9",
    "viz-merged": "#a697cc",
    "ink-good": "#8cc49a",
    "ink-warning": "#dcbd7c",
    "ink-critical": "#e39a94",
    "ink-running": "#96b7d9",
    "ink-merged": "#b8abd9",
    "ink-agent": "#86c2cf",
    "ink-muted": "#98a3ae",
    "ink-repeat": "#86c4bf",
    "ink-wakeup": "#d9a3c6",
    "mode-manual": "#98a3ae",
    "mode-plan": "#86c4bf",
    "mode-accept": "#b8abd9",
    "mode-danger": "#e39aa6",
    "mode-auto": "#dcbd7c",
    "kind-wsl": "#8cc4a3",
    "kind-windows": "#96b7d9",
    "kind-cloud": "#b8abd9",
    "kind-ssh": "#d9b27c",
  },
};
