import type { Theme } from "../types";

/**
 * Code Modern: inspired by Visual Studio Code's Dark Modern and Light Modern
 * themes. The names are Microsoft's, so the theme has its own; the colours
 * follow theirs — the #181818 / #1f1f1f dark greys and the #f8f8f8 / white
 * light ones, the #0078d4 (dark) and #005fb8 (light) buttons and focus
 * rings, and the editor's own error, warning, info and "passed" colours for
 * the states, darkened or lifted only where a word would sit under 4.5:1.
 */
export const codeModern: Theme = {
  id: "code-modern",
  name: "Code Modern",
  description:
    "Inspired by VS Code's Dark Modern and Light Modern: flat greys, the blue buttons and focus rings, the editor's state colours.",
  light: {
    background: "#f8f8f8",
    foreground: "#3b3b3b",
    card: "#ffffff",
    "card-foreground": "#3b3b3b",
    popover: "#f8f8f8",
    "popover-foreground": "#3b3b3b",
    primary: "#005fb8",
    "primary-foreground": "#ffffff",
    secondary: "#e5e5e5",
    "secondary-foreground": "#3b3b3b",
    muted: "#efefef",
    "muted-foreground": "#616161",
    accent: "#e8e8e8",
    "accent-foreground": "#1f1f1f",
    destructive: "#c72e0f",
    "destructive-foreground": "#ffffff",
    border: "#e5e5e5",
    input: "#cecece",
    ring: "#005fb8",
    favourite: "#bf8803",
    "favourite-surface": "#f5d35c",
    backdrop: "#000000",
    "badge-foreground": "#ffffff",
    "terminal-background": "#ffffff",
    "terminal-foreground": "#3b3b3b",
    "terminal-bar": "#f8f8f8",
    "terminal-bar-foreground": "#3b3b3b",
    "viz-grid": "#e5e5e5",

    "viz-muted": "#8a8a8a",
    "viz-good": "#388a34",
    "viz-warning": "#bf8803",
    "viz-critical": "#e51400",
    "viz-running": "#187aeb",
    "viz-merged": "#8a4fd0",
    "ink-good": "#2f7a2c",
    "ink-warning": "#895503",
    "ink-critical": "#c71300",
    "ink-running": "#005fb8",
    "ink-merged": "#7a2fc0",
    "ink-agent": "#257b94",
    "ink-muted": "#616161",
    "ink-repeat": "#16825d",
    "ink-wakeup": "#af00db",
    "mode-manual": "#616161",
    "mode-plan": "#16825d",
    "mode-accept": "#7a2fc0",
    "mode-danger": "#b3261e",
    "mode-auto": "#895503",
    "kind-wsl": "#2f7a2c",
    "kind-windows": "#005fb8",
    "kind-cloud": "#7a2fc0",
    "kind-ssh": "#a1520f",
  },
  dark: {
    background: "#181818",
    foreground: "#cccccc",
    card: "#1f1f1f",
    "card-foreground": "#cccccc",
    popover: "#202020",
    "popover-foreground": "#cccccc",
    primary: "#0078d4",
    "primary-foreground": "#ffffff",
    secondary: "#313131",
    "secondary-foreground": "#cccccc",
    muted: "#2b2b2b",
    "muted-foreground": "#9d9d9d",
    accent: "#2a2d2e",
    "accent-foreground": "#ffffff",
    destructive: "#f85149",
    "destructive-foreground": "#181818",
    border: "#2b2b2b",
    input: "#3c3c3c",
    ring: "#0078d4",
    favourite: "#cca700",
    "favourite-surface": "#e0c040",
    backdrop: "#000000",
    "badge-foreground": "#181818",
    "terminal-background": "#181818",
    "terminal-foreground": "#cccccc",
    "terminal-bar": "#1f1f1f",
    "terminal-bar-foreground": "#cccccc",
    "viz-grid": "#2b2b2b",

    "viz-muted": "#6e7681",
    "viz-good": "#2ea043",
    "viz-warning": "#cca700",
    "viz-critical": "#f85149",
    "viz-running": "#3794ff",
    "viz-merged": "#b180d7",
    "ink-good": "#89d185",
    "ink-warning": "#cca700",
    "ink-critical": "#f85149",
    "ink-running": "#3794ff",
    "ink-merged": "#b180d7",
    "ink-agent": "#4ec9b0",
    "ink-muted": "#9d9d9d",
    "ink-repeat": "#4ec9b0",
    "ink-wakeup": "#d670d6",
    "mode-manual": "#9d9d9d",
    "mode-plan": "#4ec9b0",
    "mode-accept": "#b180d7",
    "mode-danger": "#f14c4c",
    "mode-auto": "#cca700",
    "kind-wsl": "#89d185",
    "kind-windows": "#3794ff",
    "kind-cloud": "#b180d7",
    "kind-ssh": "#ce9178",
  },
};
