import type { Theme } from "../types";

/**
 * High Contrast: every word at 7:1 or better (WCAG AAA) on the surface it sits
 * on — prifly asks 4.5:1 of a theme, this one asks more of itself, and the
 * test holds it to that. Hairlines are dark enough to see as lines, and the
 * focus ring is a colour nothing else uses: magenta by day, yellow by night.
 */
export const highContrast: Theme = {
  id: "high-contrast",
  name: "High Contrast",
  description:
    "Black on white, white on black: every word at 7:1 or better, solid hairlines and a focus ring you cannot miss.",
  light: {
    background: "#ffffff",
    foreground: "#000000",
    card: "#ffffff",
    "card-foreground": "#000000",
    popover: "#ffffff",
    "popover-foreground": "#000000",
    primary: "#0033b3",
    "primary-foreground": "#ffffff",
    secondary: "#ebebeb",
    "secondary-foreground": "#000000",
    muted: "#ebebeb",
    "muted-foreground": "#262626",
    accent: "#d6e0ff",
    "accent-foreground": "#000000",
    destructive: "#a30000",
    "destructive-foreground": "#ffffff",
    border: "#595959",
    input: "#000000",
    ring: "#c2007a",
    favourite: "#b48300",
    "favourite-surface": "#ffd84d",
    backdrop: "#000000",
    "badge-foreground": "#ffffff",
    "terminal-background": "#000000",
    "terminal-foreground": "#ffffff",
    "terminal-bar": "#1a1a1a",
    "terminal-bar-foreground": "#ffffff",
    "viz-grid": "#8c8c8c",

    "viz-muted": "#595959",
    "viz-good": "#007a00",
    "viz-warning": "#e69500",
    "viz-critical": "#c20000",
    "viz-running": "#0047d6",
    "viz-merged": "#6a1fc2",
    "ink-good": "#005c00",
    "ink-warning": "#6b3f00",
    "ink-critical": "#990000",
    "ink-running": "#0033a0",
    "ink-merged": "#4f149c",
    "ink-agent": "#004d5c",
    "ink-muted": "#3d3d3d",
    "ink-repeat": "#004d4d",
    "ink-wakeup": "#7a0a63",
    "mode-manual": "#3d3d3d",
    "mode-plan": "#004d4d",
    "mode-accept": "#5500b3",
    "mode-danger": "#8f0020",
    "mode-auto": "#5c3d00",
    "kind-wsl": "#005c2e",
    "kind-windows": "#0033a0",
    "kind-cloud": "#4f149c",
    "kind-ssh": "#6b3f00",
  },
  dark: {
    background: "#000000",
    foreground: "#ffffff",
    card: "#000000",
    "card-foreground": "#ffffff",
    popover: "#0d0d0d",
    "popover-foreground": "#ffffff",
    primary: "#80b3ff",
    "primary-foreground": "#000000",
    secondary: "#1f1f1f",
    "secondary-foreground": "#ffffff",
    muted: "#1f1f1f",
    "muted-foreground": "#e0e0e0",
    accent: "#002e80",
    "accent-foreground": "#ffffff",
    destructive: "#ff8080",
    "destructive-foreground": "#000000",
    border: "#a6a6a6",
    input: "#ffffff",
    ring: "#ffff00",
    favourite: "#ffd400",
    "favourite-surface": "#ffe14d",
    backdrop: "#000000",
    "badge-foreground": "#000000",
    "terminal-background": "#000000",
    "terminal-foreground": "#ffffff",
    "terminal-bar": "#1f1f1f",
    "terminal-bar-foreground": "#ffffff",
    "viz-grid": "#737373",

    "viz-muted": "#a6a6a6",
    "viz-good": "#3dd13d",
    "viz-warning": "#ffc21a",
    "viz-critical": "#ff5c5c",
    "viz-running": "#66a3ff",
    "viz-merged": "#b894ff",
    "ink-good": "#66ff66",
    "ink-warning": "#ffd24d",
    "ink-critical": "#ff8a8a",
    "ink-running": "#8cbcff",
    "ink-merged": "#cdb3ff",
    "ink-agent": "#66e6ff",
    "ink-muted": "#c2c2c2",
    "ink-repeat": "#66e0e0",
    "ink-wakeup": "#ff9ce9",
    "mode-manual": "#c2c2c2",
    "mode-plan": "#66d9cc",
    "mode-accept": "#cdb3ff",
    "mode-danger": "#ff94a6",
    "mode-auto": "#ffd24d",
    "kind-wsl": "#66f0a3",
    "kind-windows": "#8cbcff",
    "kind-cloud": "#cdb3ff",
    "kind-ssh": "#ffc266",
  },
};
