import type { Theme } from "../types";

/**
 * IDE Classic: inspired by JetBrains' IDEs — Darcula for dark, IntelliJ
 * Light for light. The names are theirs, so the theme has its own; the
 * colours follow theirs:
 *
 * - dark: the #2b2b2b editor and #3c3f41 tool windows, #bbbbbb labels, the
 *   #589df6 link blue, lifted so a link reads on the code-chip grey (the
 *   #365880 default button is too dark to be link text, and prifly draws
 *   links in the primary); states from the editor scheme — string green,
 *   keyword orange, number blue, the #9876aa purple — lifted where a word
 *   would sit under 4.5:1 on the tool-window grey.
 * - light: the new UI's #f7f8fa panels around a white editor, the #3574f0
 *   accent (a step darker for the button so white text reads on it), the
 *   scheme's #0033b3 keyword blue, #067d17 string green and #871094 purple.
 */
export const ideClassic: Theme = {
  id: "ide-classic",
  name: "IDE Classic",
  description:
    "Inspired by JetBrains' Darcula (dark) and IntelliJ Light (light): the familiar greys, button blue and editor-scheme colours.",
  light: {
    background: "#f7f8fa",
    foreground: "#000000",
    card: "#ffffff",
    "card-foreground": "#000000",
    popover: "#ffffff",
    "popover-foreground": "#000000",
    primary: "#2e62d9",
    "primary-foreground": "#ffffff",
    secondary: "#ebecf0",
    "secondary-foreground": "#2b2d30",
    muted: "#ebecf0",
    "muted-foreground": "#595b61",
    accent: "#dfe1e5",
    "accent-foreground": "#000000",
    destructive: "#c9302c",
    "destructive-foreground": "#ffffff",
    border: "#dfe1e5",
    input: "#c9ccd6",
    ring: "#3574f0",
    favourite: "#af7d00",
    "favourite-surface": "#fcd462",
    backdrop: "#000000",
    "badge-foreground": "#ffffff",
    "terminal-background": "#ffffff",
    "terminal-foreground": "#000000",
    "terminal-bar": "#f7f8fa",
    "terminal-bar-foreground": "#2b2d30",
    "viz-grid": "#ebecf0",

    "viz-muted": "#8c8c8c",
    "viz-good": "#208a3c",
    "viz-warning": "#e6a200",
    "viz-critical": "#e5484d",
    "viz-running": "#3574f0",
    "viz-merged": "#a348b3",
    "ink-good": "#067d17",
    "ink-warning": "#8a5a00",
    "ink-critical": "#c21414",
    "ink-running": "#0033b3",
    "ink-merged": "#871094",
    "ink-agent": "#00627a",
    "ink-muted": "#6c707e",
    "ink-repeat": "#00736b",
    "ink-wakeup": "#a3176c",
    "ink-shell": "#a3176c",
    "ink-shell-local": "#8a5a00",
    "ink-memory": "#871094",
    "mode-manual": "#6c707e",
    "mode-plan": "#00736b",
    "mode-accept": "#871094",
    "mode-danger": "#b3203a",
    "mode-auto": "#8a5a00",
    "kind-wsl": "#067d17",
    "kind-windows": "#1750eb",
    "kind-cloud": "#871094",
    "kind-ssh": "#9e5b00",
  },
  dark: {
    background: "#2b2b2b",
    foreground: "#bbbbbb",
    card: "#3c3f41",
    "card-foreground": "#bbbbbb",
    popover: "#3c3f41",
    "popover-foreground": "#bbbbbb",
    primary: "#88baf9",
    "primary-foreground": "#1e1e1e",
    secondary: "#4c5052",
    "secondary-foreground": "#d0d0d0",
    muted: "#45494a",
    "muted-foreground": "#b8b8b8",
    accent: "#4b6eaf",
    "accent-foreground": "#ffffff",
    destructive: "#ff6b68",
    "destructive-foreground": "#1e1e1e",
    border: "#515151",
    input: "#646464",
    ring: "#4a88c7",
    favourite: "#ffc66d",
    "favourite-surface": "#e0b050",
    backdrop: "#000000",
    "badge-foreground": "#1e1e1e",
    "terminal-background": "#2b2b2b",
    "terminal-foreground": "#a9b7c6",
    "terminal-bar": "#3c3f41",
    "terminal-bar-foreground": "#bbbbbb",
    "viz-grid": "#45494a",

    "viz-muted": "#898989",
    "viz-good": "#769166",
    "viz-warning": "#cc7832",
    "viz-critical": "#e25e5b",
    "viz-running": "#6897bb",
    "viz-merged": "#9d7dae",
    "ink-good": "#8fbf73",
    "ink-warning": "#e8a060",
    "ink-critical": "#ff8683",
    "ink-running": "#8cb7e0",
    "ink-merged": "#c29fd6",
    "ink-agent": "#6ecfd6",
    "ink-muted": "#aaaaaa",
    "ink-repeat": "#72c7b6",
    "ink-wakeup": "#e38fc9",
    "ink-shell": "#e38fc9",
    "ink-shell-local": "#e8a060",
    "ink-memory": "#c29fd6",
    "mode-manual": "#aaaaaa",
    "mode-plan": "#72c7b6",
    "mode-accept": "#c29fd6",
    "mode-danger": "#ff8a8a",
    "mode-auto": "#ffc66d",
    "kind-wsl": "#8fbf73",
    "kind-windows": "#8cb7e0",
    "kind-cloud": "#c29fd6",
    "kind-ssh": "#e8a060",
  },
};
